[pytest]
testpaths = tests
addopts = -v --tb=short --alluredir=reports/allure-results --clean-alluredir
markers =
    smoke: быстрые проверки что апи живое
    regression: полный прогон всех тестов
    posts: тесты для /posts
    users: тесты для /users
    comments: тесты для /comments
    negative: негативные сценарии
